apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: t65t7gzyi-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/jsmid/rhtap-qe:a98b086dd20ea0d3d6448607921595f89891f2b4@sha256:0a5311617a2bc5da519ace5ba610efc12a462fa4e035afc11cdede5ea82c49f2
        name: container-image  
